sudo: False

language: python

python:
    - "2.7"

services:
    - mongodb

install:
    - pip install --upgrade pip
    - pip install -r requirements.txt

before_script:
    - mongo textscrolldb_test --eval 'db.addUser("travis", "test");'


script:
    - nosetests --with-coverage --with-doctest --cover-package=server
    - flake8 .

after_success:
    - coveralls

notifications:
    email:
        on_success: false
        on_failure: always
        on_start: false
