sudo: False

language: python

matrix:
  include:
    - python: "2.6"
    - python: "2.7"
    - python: "3.3"
    - python: "3.4"
    - python: "3.5"
  allow_failures:
    - python: "2.6"
    - python: "3.3"
    - python: "3.4"
    - python: "3.5"
  fast_finish: true

services:
    - mongodb

install:
    - pip install --upgrade pip
    - pip install -r requirements.txt
    - if [[ $TRAVIS_PYTHON_VERSION == 2.6 ]]; then pip install importlib; fi
    - if [[ $TRAVIS_PYTHON_VERSION < 3.4 ]]; then pip install enum34; fi

before_script:
    - mongo textscrolldb_test --eval 'db.addUser("travis", "test");'

script:
    - nosetests --with-coverage --with-doctest --cover-package=server
    - flake8 .
    - pep257 .
    - sphinx-build docs docs/_build

after_success:
    - coveralls
